# ??????????
server:
  port: 8082

shiro:
  ws:
    server:
      enable: true
      url: ""
  plugin-list:
    # - com.bot.plugin.MainPlugin  # 已删除 MainPlugin，移除注册


spring:
  application:
    name: loli_bot

  #⭐加载配置环境
  config:
    import: optional:application-local.yml
  profiles:
    active: local

  #数据库配置


#langchain4j配置
langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen3-max
        api-key:
        enable-search: true
      embedding-model:
        model-name: text-embedding-v4
        api-key: 
      streaming-chat-model:
        model-name: qwen3-max
        api-key:

